name: Deploy to AWS (OIDC)

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - staging
        default: staging
        description: "Environment to deploy"
      target_job:
        type: choice
        description: 'Which job to run?'
        options:
          - terraform-deploy
          - terraform-destroy
        required: true
        default: terraform-deploy
  # push:
  #   branches:
  #     - main
  # pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    environment: ${{ inputs.environment}}
    if: ${{ github.event.inputs.target_job == 'terraform-deploy' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_OIDC }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          export TF_VAR_db_admin_creds=${{ secrets.TF_VAR_DB_ADMIN_CREDS }}
          terraform plan --var-file=environments/staging-vars.tf -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

  terraform-destroy:
    environment: ${{ inputs.environment}}
    if: ${{ github.event.inputs.target_job == 'terraform-destroy' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_OIDC }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply --var-file=environments/staging-vars.tf -destroy -auto-approve 